version: '3'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    command: start-dev
    ports:
      - 8080:8080
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=postgres
      - DB_SCHEMA=public
      - DB_PASSWORD=postgres
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      # - KC_DB=postgres
      # - KC_DB_URL=jdbc:postgres://db:5432/keycloak
      # - KC_DB_USERNAME=postgres
      # - KC_DB_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-poc-keycloak:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "keycloak", "-h", "db", "-p", "5432"]
      interval: 5s
      timeout: 10s
      retries: 3

volumes:
  db-poc-keycloak:
